# Generated by Django 3.0.3 on 2020-03-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogpage_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='url',
            field=models.URLField(default='URL'),
        ),
    ]
